// Copyright 2017 FoxyUtils ehf. All rights reserved.
//
// DO NOT EDIT: generated by gooxml ECMA-376 generator
//
// Use of this source code is governed by the terms of the Affero GNU General
// Public License version 3.0 as published by the Free Software Foundation and
// appearing in the file LICENSE included in the packaging of this file. A
// commercial license can be purchased via https://unidoc.io website.

package math

import (
	"encoding/xml"

	"github.com/unidoc/unioffice"
)

type CT_RPRChoice struct {
	Nor *CT_OnOff
}

func NewCT_RPRChoice() *CT_RPRChoice {
	ret := &CT_RPRChoice{}
	return ret
}

func (m *CT_RPRChoice) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if m.Nor != nil {
		senor := xml.StartElement{Name: xml.Name{Local: "m:nor"}}
		e.EncodeElement(m.Nor, senor)
	}
	return nil
}

func (m *CT_RPRChoice) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	// initialize to default
lCT_RPRChoice:
	for {
		tok, err := d.Token()
		if err != nil {
			return err
		}
		switch el := tok.(type) {
		case xml.StartElement:
			switch el.Name {
			case xml.Name{Space: "http://schemas.openxmlformats.org/officeDocument/2006/math", Local: "nor"},
				xml.Name{Space: "http://purl.oclc.org/ooxml/officeDocument/math", Local: "nor"}:
				m.Nor = NewCT_OnOff()
				if err := d.DecodeElement(m.Nor, &el); err != nil {
					return err
				}
			default:
				unioffice.Log("skipping unsupported element on CT_RPRChoice %v", el.Name)
				if err := d.Skip(); err != nil {
					return err
				}
			}
		case xml.EndElement:
			break lCT_RPRChoice
		case xml.CharData:
		}
	}
	return nil
}

// Validate validates the CT_RPRChoice and its children
func (m *CT_RPRChoice) Validate() error {
	return m.ValidateWithPath("CT_RPRChoice")
}

// ValidateWithPath validates the CT_RPRChoice and its children, prefixing error messages with path
func (m *CT_RPRChoice) ValidateWithPath(path string) error {
	if m.Nor != nil {
		if err := m.Nor.ValidateWithPath(path + "/Nor"); err != nil {
			return err
		}
	}
	return nil
}
