// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// DO NOT EDIT: generated by unioffice ECMA-376 generator
//
// Use of this software package and source code is governed by the terms of the
// UniDoc End User License Agreement (EULA) that is available at:
// https://unidoc.io/eula/
// A trial license code for evaluation can be obtained at https://unidoc.io website.

package powerpoint_test

import (
	"encoding/xml"
	"testing"

	"github.com/unidoc/unioffice/schema/urn/schemas_microsoft_com/office/powerpoint"
)

func TestTextdataConstructor(t *testing.T) {
	v := powerpoint.NewTextdata()
	if v == nil {
		t.Errorf("powerpoint.NewTextdata must return a non-nil value")
	}
	if err := v.Validate(); err != nil {
		t.Errorf("newly constructed powerpoint.Textdata should validate: %s", err)
	}
}

func TestTextdataMarshalUnmarshal(t *testing.T) {
	v := powerpoint.NewTextdata()
	buf, _ := xml.Marshal(v)
	v2 := powerpoint.NewTextdata()
	xml.Unmarshal(buf, v2)
}
