//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package symex ;import (_c "encoding/xml";_d "fmt";_bb "github.com/unidoc/unioffice/v2";);func (_cc *CT_SymEx )UnmarshalXML (d *_c .Decoder ,start _c .StartElement )error {for _ ,_e :=range start .Attr {if _e .Name .Local =="\u0066\u006f\u006e\u0074"{_de :=_e .Value ;
_cc .FontAttr =&_de ;continue ;};if _e .Name .Local =="\u0063\u0068\u0061\u0072"{_bd :=_e .Value ;_cc .CharAttr =&_bd ;continue ;};};for {_a ,_da :=d .Token ();if _da !=nil {return _d .Errorf ("p\u0061r\u0073\u0069\u006e\u0067\u0020\u0043\u0054\u005fS\u0079\u006d\u0045\u0078: \u0025\u0073",_da );
};if _g ,_cd :=_a .(_c .EndElement );_cd &&_g .Name ==start .Name {break ;};};return nil ;};

// ValidateWithPath validates the SymEx and its children, prefixing error messages with path
func (_ae *SymEx )ValidateWithPath (path string )error {if _fdg :=_ae .CT_SymEx .ValidateWithPath (path );_fdg !=nil {return _fdg ;};return nil ;};func (_df *SymEx )UnmarshalXML (d *_c .Decoder ,start _c .StartElement )error {_df .CT_SymEx =*NewCT_SymEx ();
for _ ,_fb :=range start .Attr {if _fb .Name .Local =="\u0066\u006f\u006e\u0074"{_cag :=_fb .Value ;_df .FontAttr =&_cag ;continue ;};if _fb .Name .Local =="\u0063\u0068\u0061\u0072"{_fd :=_fb .Value ;_df .CharAttr =&_fd ;continue ;};};for {_bg ,_dbe :=d .Token ();
if _dbe !=nil {return _d .Errorf ("\u0070\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0053\u0079\u006d\u0045x\u003a\u0020\u0025\u0073",_dbe );};if _aa ,_abf :=_bg .(_c .EndElement );_abf &&_aa .Name ==start .Name {break ;};};return nil ;};type SymEx struct{CT_SymEx };


// Validate validates the CT_SymEx and its children
func (_f *CT_SymEx )Validate ()error {return _f .ValidateWithPath ("\u0043\u0054\u005f\u0053\u0079\u006d\u0045\u0078");};type CT_SymEx struct{FontAttr *string ;CharAttr *string ;};func NewSymEx ()*SymEx {_ccg :=&SymEx {};_ccg .CT_SymEx =*NewCT_SymEx ();
return _ccg };

// Validate validates the SymEx and its children
func (_bf *SymEx )Validate ()error {return _bf .ValidateWithPath ("\u0053\u0079\u006dE\u0078")};func NewCT_SymEx ()*CT_SymEx {_db :=&CT_SymEx {};return _db };func (_ca *CT_SymEx )MarshalXML (e *_c .Encoder ,start _c .StartElement )error {if _ca .FontAttr !=nil {start .Attr =append (start .Attr ,_c .Attr {Name :_c .Name {Local :"\u0073\u003a\u0066\u006f\u006e\u0074"},Value :_d .Sprintf ("\u0025\u0076",*_ca .FontAttr )});
};if _ca .CharAttr !=nil {start .Attr =append (start .Attr ,_c .Attr {Name :_c .Name {Local :"\u0073\u003a\u0063\u0068\u0061\u0072"},Value :_d .Sprintf ("\u0025\u0076",*_ca .CharAttr )});};e .EncodeToken (start );e .EncodeToken (_c .EndElement {Name :start .Name });
return nil ;};

// ValidateWithPath validates the CT_SymEx and its children, prefixing error messages with path
func (_ge *CT_SymEx )ValidateWithPath (path string )error {return nil };func (_ab *SymEx )MarshalXML (e *_c .Encoder ,start _c .StartElement )error {start .Attr =append (start .Attr ,_c .Attr {Name :_c .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006ff\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u00315\u002f\u0077\u006f\u0072\u0064\u006dl\u002f\u0073\u0079m\u0065\u0078"});
start .Attr =append (start .Attr ,_c .Attr {Name :_c .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006ff\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u00315\u002f\u0077\u006f\u0072\u0064\u006dl\u002f\u0073\u0079m\u0065\u0078"});
start .Attr =append (start .Attr ,_c .Attr {Name :_c .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_c .Attr {Name :_c .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0073:\u0073\u0079\u006d\u0045\u0078";return _ab .CT_SymEx .MarshalXML (e ,start );};func init (){_bb .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006ff\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u00315\u002f\u0077\u006f\u0072\u0064\u006dl\u002f\u0073\u0079m\u0065\u0078","\u0043\u0054\u005f\u0053\u0079\u006d\u0045\u0078",NewCT_SymEx );
_bb .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0073\u0063\u0068\u0065\u006d\u0061\u0073\u002e\u006d\u0069\u0063\u0072\u006fs\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006ff\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u00315\u002f\u0077\u006f\u0072\u0064\u006dl\u002f\u0073\u0079m\u0065\u0078","\u0073\u0079\u006dE\u0078",NewSymEx );
};