// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// DO NOT EDIT: generated by unioffice ECMA-376 generator
//
// Use of this source code is governed by the terms of the Affero GNU General
// Public License version 3.0 as published by the Free Software Foundation and
// appearing in the file LICENSE included in the packaging of this file. A
// commercial license can be purchased via https://unidoc.io website.

package spreadsheetDrawing_test

import (
	"encoding/xml"
	"testing"

	"github.com/unidoc/unioffice/schema/soo/dml/spreadsheetDrawing"
)

func TestCT_GraphicalObjectFrameNonVisualConstructor(t *testing.T) {
	v := spreadsheetDrawing.NewCT_GraphicalObjectFrameNonVisual()
	if v == nil {
		t.Errorf("spreadsheetDrawing.NewCT_GraphicalObjectFrameNonVisual must return a non-nil value")
	}
	if err := v.Validate(); err != nil {
		t.Errorf("newly constructed spreadsheetDrawing.CT_GraphicalObjectFrameNonVisual should validate: %s", err)
	}
}

func TestCT_GraphicalObjectFrameNonVisualMarshalUnmarshal(t *testing.T) {
	v := spreadsheetDrawing.NewCT_GraphicalObjectFrameNonVisual()
	buf, _ := xml.Marshal(v)
	v2 := spreadsheetDrawing.NewCT_GraphicalObjectFrameNonVisual()
	xml.Unmarshal(buf, v2)
}
