//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package diagram ;import (_df "encoding/xml";_b "fmt";_a "github.com/unidoc/unioffice/v2";_ea "github.com/unidoc/unioffice/v2/schema/soo/dml";_e "strconv";);

// Validate validates the CNvPr and its children
func (_aa *CNvPr )Validate ()error {return _aa .ValidateWithPath ("\u0043\u004e\u0076P\u0072")};func (_bee *CT_Boolean )UnmarshalXML (d *_df .Decoder ,start _df .StartElement )error {for _ ,_cc :=range start .Attr {if _cc .Name .Local =="\u0076\u0061\u006c"{_cg ,_bf :=_e .ParseBool (_cc .Value );
if _bf !=nil {return _bf ;};_bee .ValAttr =&_cg ;continue ;};};for {_eca ,_cce :=d .Token ();if _cce !=nil {return _b .Errorf ("\u0070\u0061\u0072\u0073in\u0067\u0020\u0043\u0054\u005f\u0042\u006f\u006f\u006c\u0065\u0061\u006e\u003a\u0020%\u0073",_cce );
};if _ed ,_gg :=_eca .(_df .EndElement );_gg &&_ed .Name ==start .Name {break ;};};return nil ;};func (_cgb *RecolorImg )UnmarshalXML (d *_df .Decoder ,start _df .StartElement )error {_cgb .CT_Boolean =*NewCT_Boolean ();for _ ,_aeb :=range start .Attr {if _aeb .Name .Local =="\u0076\u0061\u006c"{_ba ,_cga :=_e .ParseBool (_aeb .Value );
if _cga !=nil {return _cga ;};_cgb .ValAttr =&_ba ;continue ;};};for {_bea ,_bd :=d .Token ();if _bd !=nil {return _b .Errorf ("\u0070\u0061\u0072\u0073in\u0067\u0020\u0052\u0065\u0063\u006f\u006c\u006f\u0072\u0049\u006d\u0067\u003a\u0020%\u0073",_bd );
};if _efc ,_ece :=_bea .(_df .EndElement );_ece &&_efc .Name ==start .Name {break ;};};return nil ;};func (_f *RecolorImg )MarshalXML (e *_df .Encoder ,start _df .StartElement )error {start .Attr =append (start .Attr ,_df .Attr {Name :_df .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0064\u0069\u0061\u0067\u0072\u0061\u006d"});
start .Attr =append (start .Attr ,_df .Attr {Name :_df .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_df .Attr {Name :_df .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0072\u0065\u0063\u006f\u006c\u006f\u0072\u0049\u006d\u0067";return _f .CT_Boolean .MarshalXML (e ,start );};type CT_Boolean struct{ValAttr *bool ;};func NewCNvPr ()*CNvPr {_bb :=&CNvPr {};_bb .CT_NonVisualDrawingProps =*_ea .NewCT_NonVisualDrawingProps ();
return _bb ;};type CNvPr struct{_ea .CT_NonVisualDrawingProps };

// ValidateWithPath validates the CT_Boolean and its children, prefixing error messages with path
func (_aed *CT_Boolean )ValidateWithPath (path string )error {return nil };func _cgbe (_ab bool )uint8 {if _ab {return 1;};return 0;};func NewRecolorImg ()*RecolorImg {_ef :=&RecolorImg {};_ef .CT_Boolean =*NewCT_Boolean ();return _ef };func (_gc *CT_Boolean )MarshalXML (e *_df .Encoder ,start _df .StartElement )error {if _gc .ValAttr !=nil {start .Attr =append (start .Attr ,_df .Attr {Name :_df .Name {Local :"\u0076\u0061\u006c"},Value :_b .Sprintf ("\u0025\u0064",_cgbe (*_gc .ValAttr ))});
};e .EncodeToken (start );e .EncodeToken (_df .EndElement {Name :start .Name });return nil ;};func (_aff *CNvPr )UnmarshalXML (d *_df .Decoder ,start _df .StartElement )error {_aff .CT_NonVisualDrawingProps =*_ea .NewCT_NonVisualDrawingProps ();for {_be ,_ec :=d .Token ();
if _ec !=nil {return _b .Errorf ("\u0070\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0043\u004e\u0076\u0050r\u003a\u0020\u0025\u0073",_ec );};if _bef ,_g :=_be .(_df .EndElement );_g &&_bef .Name ==start .Name {break ;};};return nil ;};

// Validate validates the RecolorImg and its children
func (_cd *RecolorImg )Validate ()error {return _cd .ValidateWithPath ("\u0052\u0065\u0063\u006f\u006c\u006f\u0072\u0049\u006d\u0067");};func (_af *CNvPr )MarshalXML (e *_df .Encoder ,start _df .StartElement )error {start .Attr =append (start .Attr ,_df .Attr {Name :_df .Name {Local :"\u0078\u006d\u006cn\u0073"},Value :"\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0064\u0069\u0061\u0067\u0072\u0061\u006d"});
start .Attr =append (start .Attr ,_df .Attr {Name :_df .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0077\u00314"},Value :"\u0068\u0074t\u0070\u003a\u002f\u002f\u0073c\u0068\u0065\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002e\u0063\u006f\u006d\u002f\u006f\u0066\u0066\u0069\u0063\u0065\u002f\u0077\u006f\u0072\u0064\u002f\u0032\u0030\u0031\u0030\u002f\u0077\u006f\u0072\u0064\u006d\u006c"});
start .Attr =append (start .Attr ,_df .Attr {Name :_df .Name {Local :"\u0078m\u006c\u006e\u0073\u003a\u0078\u006dl"},Value :"\u0068\u0074tp\u003a\u002f\u002fw\u0077\u0077\u002e\u00773.o\u0072g/\u0058\u004d\u004c\u002f\u0031\u0039\u00398/\u006e\u0061\u006d\u0065\u0073\u0070\u0061c\u0065"});
start .Name .Local ="\u0063\u004e\u0076P\u0072";return _af .CT_NonVisualDrawingProps .MarshalXML (e ,start );};

// ValidateWithPath validates the CNvPr and its children, prefixing error messages with path
func (_eae *CNvPr )ValidateWithPath (path string )error {if _ee :=_eae .CT_NonVisualDrawingProps .ValidateWithPath (path );_ee !=nil {return _ee ;};return nil ;};func NewCT_Boolean ()*CT_Boolean {_c :=&CT_Boolean {};return _c };type RecolorImg struct{CT_Boolean };


// Validate validates the CT_Boolean and its children
func (_ae *CT_Boolean )Validate ()error {return _ae .ValidateWithPath ("\u0043\u0054\u005f\u0042\u006f\u006f\u006c\u0065\u0061\u006e");};

// ValidateWithPath validates the RecolorImg and its children, prefixing error messages with path
func (_fd *RecolorImg )ValidateWithPath (path string )error {if _fdb :=_fd .CT_Boolean .ValidateWithPath (path );_fdb !=nil {return _fdb ;};return nil ;};func init (){_a .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0064\u0069\u0061\u0067\u0072\u0061\u006d","\u0043\u0054\u005f\u0042\u006f\u006f\u006c\u0065\u0061\u006e",NewCT_Boolean );
_a .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0064\u0069\u0061\u0067\u0072\u0061\u006d","\u0063\u004e\u0076P\u0072",NewCNvPr );
_a .RegisterConstructor ("\u0068\u0074\u0074\u0070\u003a\u002f/\u0073\u0063\u0068e\u006d\u0061\u0073.\u006d\u0069\u0063\u0072\u006f\u0073\u006f\u0066\u0074\u002ec\u006f\u006d\u002f\u006f\u0066fi\u0063\u0065\u002f\u0064\u0072\u0061\u0077\u0069\u006e\u0067\u002f\u0032\u0030\u0031\u0030\u002f\u0064\u0069\u0061\u0067\u0072\u0061\u006d","\u0072\u0065\u0063\u006f\u006c\u006f\u0072\u0049\u006d\u0067",NewRecolorImg );
};