//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package utils ;import (_e "bytes";_b "github.com/unidoc/unioffice/document";_fb "github.com/unidoc/unioffice/document/convert";_fg "github.com/unidoc/unipdf/v3/model";);

// GetNumPages will try to get actual document page count by converting the document to a PDF first
// and then get the actual page count from the PDF result.
//
// WARNING: This method is currently in experimental state as the PDF result might have incorrect page count.
func GetNumPages (d *_b .Document )(int ,error ){var _bg _e .Buffer ;_a :=_fb .ConvertToPdf (d );if _g :=_a .Write (&_bg );_g !=nil {return 0,_g ;};_c ,_gc :=_fg .NewPdfReader (_e .NewReader (_bg .Bytes ()));if _gc !=nil {return 0,_gc ;};_ce ,_gc :=_c .GetNumPages ();
if _gc !=nil {return 0,_gc ;};return _ce ,nil ;};