// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// DO NOT EDIT: generated by unioffice ECMA-376 generator
//
// Use of this software package and source code is governed by the terms of the
// UniDoc End User License Agreement (EULA) that is available at:
// https://unidoc.io/eula/
// A trial license code for evaluation can be obtained at https://unidoc.io website.

package elements_test

import (
	"encoding/xml"
	"testing"

	"github.com/unidoc/unioffice/schema/purl.org/dc/elements"
)

func TestElementsGroupConstructor(t *testing.T) {
	v := elements.NewElementsGroup()
	if v == nil {
		t.Errorf("elements.NewElementsGroup must return a non-nil value")
	}
	if err := v.Validate(); err != nil {
		t.Errorf("newly constructed elements.ElementsGroup should validate: %s", err)
	}
}

func TestElementsGroupMarshalUnmarshal(t *testing.T) {
	v := elements.NewElementsGroup()
	buf, _ := xml.Marshal(v)
	v2 := elements.NewElementsGroup()
	xml.Unmarshal(buf, v2)
}
