//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package algo ;func RepeatString (s string ,cnt int )string {if cnt <=0{return "";};_d :=make ([]byte ,len (s )*cnt );_g :=[]byte (s );for _gc :=0;_gc < cnt ;_gc ++{copy (_d [_gc :],_g );};return string (_d );};